### ISSUE TITLE
ἐπι-κῠλινδέω no definition

### ISSUE THREAD

**Issue by vgorman1** [alpheios-project/morpheus#36] opened 2020-11-03 18:38 UTC
ἐπεκυλίνδουν is analyzed (correctly) as ἐπι-κῠλινδέω, but then it says NO DEFINITIONS FOUND. Is the hyphen messing it up?

**Comment by balmas** [comment] 2020-12-10 15:05
dupe of alpheios-project/alpheios-core#572

**Closed as completed by balmas** 2020-12-10 15:05 UTC
Labels: bug, duplicate
